FROM nginx:1.17.1-alpine

COPY  ./dist/ /usr/share/nginx/html

COPY  ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]