import type { SelectItem } from '@/types';

export const INCIDENCES: string[] = [
  'CONDUCIR BAJO LOS EFECTOS DEL ALCOHOL O DROGAS',
  'VIOLACIONES DE TRAFICO',
  'INCUMPLIMIENTO DE REGLAMENTACIONES DE SEGURIDAD',
  'MANTENIMIENTO DEFICIENTE DEL VEHICULO',
  'CONDUCTA AGRESIVA O IMPRUDENTE',
  'INCUMPLIMIENTO DE NORMAS DE CARGA Y PESO',
  'DOCUMENTACION Y REGISTROS INCORRECTOS',
  'OPERADOR NO QUISO HACER UNA MANIOBRA',
  'OPERADOR DEJO BOTADA LA MANIOBRA',
  'NO TOMO EQUIPO ASIGNADO',
  'OTRO',
];

export const INCIDENCE_OPTIONS: SelectItem[] = INCIDENCES.map((r) => ({
  key: r,
  value: r,
}));

