import type { SelectItem } from '@/types';

export const OPERATIVE_INCIDENCES: string[] = [
  'INCUMPLIMIENTO DE REGLAMENTO DE SEGURIDAD',
  'CONDUCTA AGRESIVA O IMPRUDENTE',
  'OPERADOR NO QUISO HACER MANIOBRA',
  'OPERADOR DEJA BOTADA MANIOBRA NO TOMO EQUIPO ASIGNADO',
  'DEJO VIAJE BOTADO',
  'OTRO',
];

export const LEGAL_INCIDENCES: string[] = [
  'COLISIÓN',
  'VOLCADURA',
  'CONDUCIR BAJO LOS EFECTOS DEL ALCOHOL O DROGAS',
  'VIOLACIONES DE TRAFICO',
  'MANTENIMIENTO DEFICIENTE DEL VEHICULO',
  'INCUMPLIMIENTO DE REGLAMENTACIONES DE SEGURIDAD',
  'DOCUMENTACION Y REGISTROS INCORRECTOS',
  'OTRO',
];

export const LEGAL_INCIDENCE_OPTIONS: SelectItem[] = LEGAL_INCIDENCES.map(
  (r) => ({
    key: r,
    value: r,
  }),
);

export const OPERATIVE_INCIDENCE_OPTIONS: SelectItem[] =
  OPERATIVE_INCIDENCES.map((r) => ({
    key: r,
    value: r,
  }));

